name: mri

on:
  push:
    branches: ["main"]

    jobs:
      build: 
        runs-on: ubuntu-latest
        stpes:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Python 3.11
              uses: action/setup-python@v3
              with:
                python-version: "3.11"

            - name: Install Dependencies
              run: 
                python -m pip install --upgrade pip
                pip install flask8 pytest
                if [ -f req_production.txt]; then pip install -r req_production.txt;
